name: Deploy Tailwind Kit Storybook

concurrency:
  group: ui-kit-deployment
  cancel-in-progress: false

on:
  push:
    branches:
      - main
    paths:
      - "packages/tailwind-kit/**"
      - "packages/tokens/**"
      - ".github/workflows/deploy-tailwind-kit.yml"

  workflow_run:
    workflows: ["Deploy React Kit Storybook"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/tailwind-kit
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies in root
        run: pnpm install
        working-directory: .

      - name: Install dependencies in package
        run: pnpm install

      # Сборка tokens с правильным путем
      - name: Build tokens package
        working-directory: ${{ github.workspace }}/packages/tokens
        run: pnpm build

      # Создаем директории для выходных файлов
      - name: Create directories
        run: |
          mkdir -p src
          mkdir -p dist
          mkdir -p storybook-static

      # Создаём простой CSS файл напрямую
      - name: Create CSS file
        run: |
          cat > dist/styles.css << 'EOFCSS'
          /* Базовые стили */
          :root {
            --color-primary: oklch(65% 0.25 30deg);
            --color-secondary: oklch(75% 0.22 210deg);
            --color-accent: oklch(75% 0.3 320deg);
          }

          .button {
            padding: 8px 16px;
            border-radius: 4px;
            font-weight: bold;
            cursor: pointer;
          }

          .button-primary {
            background-color: var(--color-primary);
            color: white;
          }

          .button-secondary {
            background-color: var(--color-secondary);
            color: white;
          }
          EOFCSS

          # Копируем CSS в директорию storybook
          cp dist/styles.css storybook-static/

      # Создаем простую демо-страницу
      - name: Create demo page
        run: |
          cat > storybook-static/index.html << 'EOFHTML'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Tailwind Kit Demo</title>
            <link rel="stylesheet" href="styles.css">
          </head>
          <body style="padding: 20px; font-family: system-ui, sans-serif;">
            <h1>Tailwind Kit Components</h1>
            <div style="margin-top: 20px;">
              <h2>Buttons</h2>
              <div style="display: flex; gap: 10px;">
                <button class="button button-primary">Primary Button</button>
                <button class="button button-secondary">Secondary Button</button>
              </div>
            </div>
          </body>
          </html>
          EOFHTML

      # Пробуем собрать Storybook
      - name: Try to build Storybook
        continue-on-error: true
        run: |
          # Добавляем необходимые зависимости для Storybook HTML
          pnpm add -D @storybook/html @storybook/html-webpack5
          # Пробуем собрать Storybook
          pnpm build-storybook

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./packages/tailwind-kit/storybook-static
          destination_dir: tailwind-kit
